[package]
name = "decibel-trading-starter-kit-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
aptos-rust-sdk-v2 = { git = "https://github.com/aptos-labs/aptos-rust-sdk.git", rev = "a2a5dd4893554fe4f069727897b75ceb1cf99c74", package = "aptos-rust-sdk-v2" }
